"""Add UTR settings for BED types

Revision ID: 03052354c8b6
Revises: c73425212377
Create Date: <timestamp>

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03052354c8b6'
down_revision = 'c73425212377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        # Add UTR columns
        batch_op.add_column(sa.Column('data_include_5utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('data_include_3utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('sambamba_include_5utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('sambamba_include_3utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('exomeDepth_include_5utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('exomeDepth_include_3utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('cnv_include_5utr', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('cnv_include_3utr', sa.Boolean(), nullable=True, server_default='0'))

        # Add padding columns back (they will be populated from profile_settings)
        batch_op.add_column(sa.Column('data_padding', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('sambamba_padding', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('exomeDepth_padding', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('cnv_padding', sa.Integer(), nullable=True, server_default='0'))

    # Migrate data from profile_settings to individual columns
    connection = op.get_bind()
    settings_table = sa.Table(
        'settings',
        sa.MetaData(),
        sa.Column('id', sa.Integer()),
        sa.Column('profile_settings', sa.JSON()),
        sa.Column('data_padding', sa.Integer()),
        sa.Column('sambamba_padding', sa.Integer()),
        sa.Column('exomeDepth_padding', sa.Integer()),
        sa.Column('cnv_padding', sa.Integer())
    )
    
    for settings in connection.execute(settings_table.select()):
        if settings.profile_settings:
            profile_settings = settings.profile_settings
            connection.execute(
                settings_table.update().
                where(settings_table.c.id == settings.id).
                values(
                    data_padding=profile_settings.get('data', {}).get('padding', 0),
                    sambamba_padding=profile_settings.get('sambamba', {}).get('padding', 0),
                    exomeDepth_padding=profile_settings.get('exome_depth', {}).get('padding', 0),
                    cnv_padding=profile_settings.get('cnv', {}).get('padding', 0)
                )
            )

    # Drop profile_settings column
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('profile_settings')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        # Recreate profile_settings column
        batch_op.add_column(sa.Column('profile_settings', sa.JSON(), nullable=True))

        # Drop UTR columns
        batch_op.drop_column('cnv_include_3utr')
        batch_op.drop_column('cnv_include_5utr')
        batch_op.drop_column('exomeDepth_include_3utr')
        batch_op.drop_column('exomeDepth_include_5utr')
        batch_op.drop_column('sambamba_include_3utr')
        batch_op.drop_column('sambamba_include_5utr')
        batch_op.drop_column('data_include_3utr')
        batch_op.drop_column('data_include_5utr')

        # Drop padding columns
        batch_op.drop_column('cnv_padding')
        batch_op.drop_column('exomeDepth_padding')
        batch_op.drop_column('sambamba_padding')
        batch_op.drop_column('data_padding')

    # ### end Alembic commands ###