"""Add SNP padding settings

Revision ID: 3467b49b34cd
Revises: ebb20169be05
Create Date: 2024-11-26 10:42:26.474144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3467b49b34cd'
down_revision = 'ebb20169be05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_snp_padding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sambamba_snp_padding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exomeDepth_snp_padding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cnv_snp_padding', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('cnv_snp_padding')
        batch_op.drop_column('exomeDepth_snp_padding')
        batch_op.drop_column('sambamba_snp_padding')
        batch_op.drop_column('data_snp_padding')

    # ### end Alembic commands ###
