"""Add UTR inclusion columns to BedFile

Revision ID: 35d6835fbaf8
Revises: 4ee76151a4b6
Create Date: 2024-10-17 17:19:52.735406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d6835fbaf8'
down_revision = '4ee76151a4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_3utr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('include_5utr', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.drop_column('include_5utr')
        batch_op.drop_column('include_3utr')

    # ### end Alembic commands ###
