"""Add initial_query to BedFile

Revision ID: 4ee76151a4b6
Revises: 6ed3cbad7b03
Create Date: 2024-10-14 11:16:42.242486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee76151a4b6'
down_revision = '6ed3cbad7b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_query', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.drop_column('initial_query')

    # ### end Alembic commands ###
