"""Add ExportType model and update Settings

Revision ID: 6a06a48e6f48
Revises: a082711d385e
Create Date: 2024-11-13 17:09:45.893244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a06a48e6f48'
down_revision = 'a082711d385e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('sambamba_padding')
        batch_op.drop_column('data_padding')
        batch_op.drop_column('exomeDepth_padding')
        batch_op.drop_column('cnv_padding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnv_padding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('exomeDepth_padding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('data_padding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sambamba_padding', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
