"""Add assembly column to bed_file table

Revision ID: 6ed3cbad7b03
Revises: 2363d18d116a
Create Date: 2024-10-14 11:04:15.398836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed3cbad7b03'
down_revision = '2363d18d116a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assembly', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.drop_column('assembly')

    # ### end Alembic commands ###
