"""Add file_blob column to bed_file table

Revision ID: 8305470351f0
Revises: 
Create Date: 2024-12-04 09:42:08.290601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8305470351f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_entry', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('settings')
        batch_op.drop_column('bed_type')

    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_blob', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.drop_column('file_blob')

    with op.batch_alter_table('bed_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bed_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
