"""Add SNP padding fields

Revision ID: 85f66015e00d
Revises: 3467b49b34cd
Create Date: 2024-11-26 10:49:55.346540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f66015e00d'
down_revision = '3467b49b34cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_settings')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('data_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sambamba_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exomeDepth_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cnv_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('cnv_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exomeDepth_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sambamba_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('data_snp_padding',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_include_5utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('data_include_3utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('sambamba_include_5utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('sambamba_include_3utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('exomeDepth_include_5utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('exomeDepth_include_3utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('cnv_include_5utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('cnv_include_3utr', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('data_padding', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('sambamba_padding', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('exomeDepth_padding', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('cnv_padding', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('data_snp_padding', sa.INTEGER(), nullable=False),
    sa.Column('sambamba_snp_padding', sa.INTEGER(), nullable=False),
    sa.Column('exomeDepth_snp_padding', sa.INTEGER(), nullable=False),
    sa.Column('cnv_snp_padding', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
