"""Add warning column to bed_file table

Revision ID: a082711d385e
Revises: 35d6835fbaf8
Create Date: 2024-11-01 09:57:38.234749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a082711d385e'
down_revision = '35d6835fbaf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning', sa.String(length=255), nullable=True))

    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_file', schema=None) as batch_op:
        batch_op.drop_column('warning')

    with op.batch_alter_table('bed_entry', schema=None) as batch_op:
        batch_op.drop_column('warning')

    # ### end Alembic commands ###
