"""db setup

Revision ID: a201e0003c9e
Revises: 
Create Date: 2024-12-04 15:11:01.069217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a201e0003c9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_padding', sa.Integer(), nullable=True),
    sa.Column('sambamba_padding', sa.Integer(), nullable=True),
    sa.Column('exomeDepth_padding', sa.Integer(), nullable=True),
    sa.Column('cnv_padding', sa.Integer(), nullable=True),
    sa.Column('data_include_5utr', sa.Boolean(), nullable=True),
    sa.Column('data_include_3utr', sa.Boolean(), nullable=True),
    sa.Column('sambamba_include_5utr', sa.Boolean(), nullable=True),
    sa.Column('sambamba_include_3utr', sa.Boolean(), nullable=True),
    sa.Column('exomeDepth_include_5utr', sa.Boolean(), nullable=True),
    sa.Column('exomeDepth_include_3utr', sa.Boolean(), nullable=True),
    sa.Column('cnv_include_5utr', sa.Boolean(), nullable=True),
    sa.Column('cnv_include_3utr', sa.Boolean(), nullable=True),
    sa.Column('data_snp_padding', sa.Integer(), nullable=False),
    sa.Column('sambamba_snp_padding', sa.Integer(), nullable=False),
    sa.Column('exomeDepth_snp_padding', sa.Integer(), nullable=False),
    sa.Column('cnv_snp_padding', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_authorizer', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('bed_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('authorizer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('assembly', sa.String(length=10), nullable=True),
    sa.Column('initial_query', sa.Text(), nullable=True),
    sa.Column('include_3utr', sa.Boolean(), nullable=True),
    sa.Column('include_5utr', sa.Boolean(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('file_blob', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['authorizer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bed_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bed_file_id', sa.Integer(), nullable=False),
    sa.Column('chromosome', sa.String(length=50), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('entrez_id', sa.String(length=50), nullable=True),
    sa.Column('gene', sa.String(length=100), nullable=True),
    sa.Column('accession', sa.String(length=50), nullable=True),
    sa.Column('exon_id', sa.String(length=50), nullable=True),
    sa.Column('exon_number', sa.Integer(), nullable=True),
    sa.Column('transcript_biotype', sa.String(length=50), nullable=True),
    sa.Column('mane_transcript', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bed_file_id'], ['bed_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bed_entry')
    op.drop_table('bed_file')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('settings')
    # ### end Alembic commands ###
