"""Add UTR settings for BED types

Revision ID: b42377b4f699
Revises: 6a06a48e6f48
Create Date: 2024-11-22 16:27:14.863339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42377b4f699'
down_revision = '6a06a48e6f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_type')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_padding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sambamba_padding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exomeDepth_padding', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cnv_padding', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('cnv_padding')
        batch_op.drop_column('exomeDepth_padding')
        batch_op.drop_column('sambamba_padding')
        batch_op.drop_column('data_padding')

    op.create_table('export_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('padding', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('button_class', sa.VARCHAR(length=50), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
