"""Update settings structure

Revision ID: c73425212377
Revises: b42377b4f699
Create Date: 2024-11-22 16:46:59.437781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73425212377'
down_revision = 'b42377b4f699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_settings', sa.JSON(), nullable=True))
        batch_op.drop_column('data_padding')
        batch_op.drop_column('cnv_padding')
        batch_op.drop_column('exomeDepth_padding')
        batch_op.drop_column('sambamba_padding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sambamba_padding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('exomeDepth_padding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cnv_padding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('data_padding', sa.INTEGER(), nullable=True))
        batch_op.drop_column('profile_settings')

    # ### end Alembic commands ###
