"""Change warning to status in BedEntry

Revision ID: ebb20169be05
Revises: 03052354c8b6
Create Date: 2024-11-26 10:35:19.059104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb20169be05'
down_revision = '03052354c8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))
        batch_op.drop_column('warning')
        batch_op.drop_column('mane_transcript_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bed_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mane_transcript_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('warning', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
